SELECT  A.ITEM_ID AS ITEM_ID,
        A.ITEM_NAME AS ITEM_NAME,
        A.RARITY AS RARITY
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE B.ITEM_ID IS NULL
ORDER BY A.ITEM_ID DESC