WITH RANKED AS (
    SELECT
        FOOD_TYPE,
        REST_ID,
        REST_NAME,
        FAVORITES,
        ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RAN
    FROM REST_INFO
)
SELECT 
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM RANKED
WHERE 
    RAN = 1
ORDER BY
    FOOD_TYPE DESC
