SELECT 
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    ui.GENDER,
    COUNT(DISTINCT os.USER_ID) AS USERS
FROM USER_INFO ui
JOIN 
    ONLINE_SALE os ON ui.USER_ID = os.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    YEAR, MONTH, GENDER
ORDER BY
    YEAR, MONTH, GENDER