SELECT  a.APNT_NO AS APNT_NO,
        p.PT_NAME AS PT_NAME,
        p.PT_NO AS PT_NO,
        a.MCDP_CD AS MCDP_CD,
        d.DR_NAME AS DR_NAME,
        a.APNT_YMD AS APNT_YMD
FROM PATIENT p
INNER JOIN APPOINTMENT a ON p.PT_NO = a.PT_NO
INNER JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
WHERE DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND a.APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD