SELECT  YEAR(B.DIFFERENTIATION_DATE) AS YEAR,
        A.max_length - B.SIZE_OF_COLONY AS YEAR_DEV,
        B.ID AS ID
FROM (
    SELECT  YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS 'max_length'
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) A
INNER JOIN ECOLI_DATA B ON A.YEAR = YEAR(B.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC , YEAR_DEV ASC;