SELECT
    SUM(g.SCORE) AS SCORE,
    e.EMP_NO,
    e.EMP_NAME,
    e.POSITION,
    e.EMAIL
FROM HR_EMPLOYEES e
JOIN
    HR_GRADE g ON e.EMP_NO = g.EMP_NO
WHERE YEAR = 2022
GROUP BY
    EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
ORDER BY SCORE DESC
LIMIT 1