SELECT
    ice.INGREDIENT_TYPE,
    SUM(fh.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF fh
JOIN
    ICECREAM_INFO ice ON fh.FLAVOR = ice.FLAVOR
GROUP BY 
    ice.INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER
