SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/', B.FILE_ID, B.FILE_NAME, B.FILE_EXT) AS FILE_PATH
FROM (
    SELECT  BOARD_ID,
            RANK() OVER(ORDER BY VIEWS DESC) AS VIEW_RANK
    FROM USED_GOODS_BOARD
) A
INNER JOIN USED_GOODS_FILE B ON A.BOARD_ID = B.BOARD_ID
WHERE A.VIEW_RANK = 1
ORDER BY B.FILE_ID DESC